version: "3"

services:
  tomcat:
    image: tomcat:8.0
    ports:
      - 8888:8080
    expose:
      - 8080

  java:
    image: java:8
    # ports:
    #   - 8888:8080
    # expose:
    #   - 8080
    volumes:
      - ${APP_PATH}:/tmp/app
